# Core Colors
background            #131413
foreground            #e4e2e1
selection_foreground  #b5cbc5
selection_background  #203430
cursor                #b5cbc5
cursor_text_color     #131413

# Regular Colors
color0  #131413
color1  #ffb4ab
color2  #b5cbc5
color3  #c8c4d9
color4  #d1e7e0
color5  #dae2de
color6  #c0c8c5
color7  #e4e2e1

# Bright Colors
color8  #393939
color9  #ffb4ab
color10 #b5cbc5
color11 #c8c4d9
color12 #d1e7e0
color13 #dae2de 
color14 #c0c8c5
color15 #e4e2e1

# Font
font_family	JetBrainsMono
font_size 12.0

# Spacing
window_padding_width 13.0
