# Core Colors
background            #111415
foreground            #e1e3e3
selection_foreground  #94d0dc
selection_background  #00363e
cursor                #94d0dc
cursor_text_color     #111415

# Regular Colors
color0  #111415
color1  #ffb4ab
color2  #94d0dc
color3  #d5bdf1
color4  #b3b3b3
color5  #d0e8ed
color6  #b3cbd0
color7  #e1e3e3

# Bright Colors
color8  #373a3a
color9  #ffb4ab
color10 #94d0dc
color11 #d5bdf1
color12  #b3b3b3
color13 #d0e8ed 
color14 #b3cbd0
color15 #e1e3e3

# Font
font_family	JetBrainsMono
font_size 12.0

# Spacing
window_padding_width 13.0
