[config.wallpaper]
command = "swww img {{ image }} --transition-type any --transition-fps 60"
set = true

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/kitty.conf'
post_hook = "kill -SIGUSR1 $(pidof kitty)"

[templates.vscode]
input_path = '~/.config/matugen/templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'
post_hook = "jq -s '.[0] * .[1]' ~/.config/Code/User/settings.json ~/.cache/matugen/vscode-colors.json > ~/.config/Code/User/settings.json.tmp && mv ~/.config/Code/User/settings.json.tmp ~/.config/Code/User/settings.json"

[templates.newtab]
input_path = '~/.config/matugen/templates/newtab.html'
output_path = '~/.config/newtab.html'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/shared/colors.rasi'

[templates.cava]
input_path = '~/.config/matugen/templates/matugen-cava'
output_path = '~/.config/cava/config'
post_hook = "pkill -USR1 cava"

[templates.zathura]
input_path = '~/.config/matugen/templates/zathurarc'
output_path = '~/.config/zathura/zathurarc'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spotify-colors.ini'
output_path = '~/.config/spicetify/Themes/text/color.ini'

[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/matugen.css'
