input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 1
    accel_profile = flat
    force_no_accel = 0
    
    touchpad {
        natural_scroll = 1
        scroll_factor = 0.5
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = elan-trackpoint
    accel_profile = adaptive
    sensitivity = 0
    scroll_factor = 1
}
